// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCR6Dg9bRRibhpJVGruxAbZEd0rZfSabQ',
    appId: '1:756488055954:web:8742895ef865b7a321ca4b',
    messagingSenderId: '756488055954',
    projectId: 'cure-178d8',
    authDomain: 'cure-178d8.firebaseapp.com',
    storageBucket: 'cure-178d8.firebasestorage.app',
    measurementId: 'G-9N0LJBJX7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKGXx6RoyqwbK8vRYrtrPHtyi56rd1uU',
    appId: '1:756488055954:android:751aee334296b73f21ca4b',
    messagingSenderId: '756488055954',
    projectId: 'cure-178d8',
    storageBucket: 'cure-178d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJpzFhkIMznu2MH3-u7IkdMDCZSpGUhcY',
    appId: '1:756488055954:ios:13a16ad07bd236da21ca4b',
    messagingSenderId: '756488055954',
    projectId: 'cure-178d8',
    storageBucket: 'cure-178d8.firebasestorage.app',
    iosBundleId: 'com.example.cuerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJpzFhkIMznu2MH3-u7IkdMDCZSpGUhcY',
    appId: '1:756488055954:ios:13a16ad07bd236da21ca4b',
    messagingSenderId: '756488055954',
    projectId: 'cure-178d8',
    storageBucket: 'cure-178d8.firebasestorage.app',
    iosBundleId: 'com.example.cuerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCR6Dg9bRRibhpJVGruxAbZEd0rZfSabQ',
    appId: '1:756488055954:web:9b2f2d4e9929387d21ca4b',
    messagingSenderId: '756488055954',
    projectId: 'cure-178d8',
    authDomain: 'cure-178d8.firebaseapp.com',
    storageBucket: 'cure-178d8.firebasestorage.app',
    measurementId: 'G-RCJXCHBN69',
  );
}
